codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: code_cov_test_branch  # only use the latest copy on main branch #TODO:change to master

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 90%
    patch:
      default:
        enabled: yes
        target: 90%
